In [52]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

# Training
- load the dataset
- basic preprocessing
- training Process
  - create the model
  - forward pass
  - loss calculation
  - backpropagation
  - parameter update
- Model evaluation

In [53]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [54]:
df.shape

(569, 33)

In [55]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace= True)

In [56]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

#Scaling

In [57]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [58]:
X_train

array([[ 0.88601897,  0.90280253,  0.7569377 , ..., -0.50827083,
        -0.73786861, -1.01225603],
       [-0.80481647,  1.85730948, -0.84129562, ..., -1.44978687,
        -0.09976324, -0.70616967],
       [-0.16269157,  1.35868645, -0.17780885, ...,  0.04344655,
        -0.41801227, -0.54028371],
       ...,
       [-1.48675872, -1.09643839, -1.36955979, ..., -1.03611362,
        -1.05611763,  1.30212073],
       [ 1.19446324,  0.62974706,  1.13165091, ...,  0.34187897,
         0.31813951, -0.426304  ],
       [-0.34495409, -0.22978407, -0.33543278, ..., -0.7572706 ,
         0.47565671, -0.62055111]])

In [59]:
y_train

261    M
231    B
100    M
138    M
153    B
      ..
463    B
469    B
71     B
134    M
402    B
Name: diagnosis, Length: 455, dtype: object

In [60]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [61]:
y_train

array([1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,

# Numpy arrays to PyTrorch Tensor

In [62]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [63]:
X_train_tensor.shape

torch.Size([455, 30])

In [64]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

In [65]:
class MySimpleNN():

  def __init__(self, X):
    ''' we are setting random values to weights and zero to bias and also set requires_grad=True '''
    self.weights = torch.rand(X.shape[1],1, dtype = torch.float64, requires_grad=True)  # initialized by wandom values
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
      z = torch.matmul(X, self.weights) + self.bias
      y_pred = torch.sigmoid(z)
      return y_pred

  def loss_function(self, y_pred , y):
      epsilon = 1e-7
      y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

      # Calculate loss
      loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1-y_pred)).mean()
      return loss


In [71]:
learning_rate = 0.1
epochs = 60

In [72]:
model.weights

tensor([[ 0.0079],
        [-0.0697],
        [-0.3487],
        [ 0.6422],
        [ 0.2400],
        [-0.3343],
        [ 0.0649],
        [-0.3352],
        [-0.0465],
        [ 0.0267],
        [-0.3439],
        [ 0.3503],
        [ 0.3800],
        [ 0.5226],
        [-0.1627],
        [ 0.4640],
        [-0.1214],
        [-0.4387],
        [ 0.3822],
        [ 0.0365],
        [-0.1314],
        [-0.0954],
        [ 0.1018],
        [-0.1056],
        [ 0.4083],
        [-0.3759],
        [ 0.3017],
        [-0.1867],
        [ 0.4540],
        [-0.3640]], dtype=torch.float64, requires_grad=True)

In [73]:
model.bias

tensor([-0.2078], dtype=torch.float64, requires_grad=True)

# Training Pipeline

In [74]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.449935759320477
Epoch: 2, Loss: 3.332775133660972
Epoch: 3, Loss: 3.209875808567273
Epoch: 4, Loss: 3.0850409287425062
Epoch: 5, Loss: 2.9600636781060823
Epoch: 6, Loss: 2.83288566712239
Epoch: 7, Loss: 2.707999837560977
Epoch: 8, Loss: 2.584157246826949
Epoch: 9, Loss: 2.4596597421135913
Epoch: 10, Loss: 2.3317739424590234
Epoch: 11, Loss: 2.20421175103395
Epoch: 12, Loss: 2.0757899983026924
Epoch: 13, Loss: 1.950022670944711
Epoch: 14, Loss: 1.8295941539371845
Epoch: 15, Loss: 1.7125561976263068
Epoch: 16, Loss: 1.6016218934940876
Epoch: 17, Loss: 1.4986681909212658
Epoch: 18, Loss: 1.4041575027162407
Epoch: 19, Loss: 1.3201062252937834
Epoch: 20, Loss: 1.2462731927987951
Epoch: 21, Loss: 1.1820973749971875
Epoch: 22, Loss: 1.1267431967000934
Epoch: 23, Loss: 1.0792226330153345
Epoch: 24, Loss: 1.0385285307053367
Epoch: 25, Loss: 1.003709699400297
Epoch: 26, Loss: 0.9738802273168977
Epoch: 27, Loss: 0.948212309789054
Epoch: 28, Loss: 0.9259546988624907
Epoch: 29, Lo

In [75]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6666666865348816
