In [63]:
#create model class
import torch
import torch.nn as nn

In [64]:
# create model class
class Model(nn.Module):
  def __init__ (self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [65]:
# create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model for forward pass

# model.forward(features)
model(features)

tensor([[0.4930],
        [0.4658],
        [0.5403],
        [0.5117],
        [0.5034],
        [0.5403],
        [0.4662],
        [0.4553],
        [0.4732],
        [0.5173]], grad_fn=<SigmoidBackward0>)

In [66]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.1016, -0.2208,  0.3830,  0.0874,  0.1976]], requires_grad=True)

In [67]:
#show model bias
model.linear.bias

Parameter containing:
tensor([-0.2550], requires_grad=True)

In [68]:
!pip install torchinfo

In [69]:
from torchinfo import summary
summary(model , input_size =(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [70]:
# create model with hidden network
class MLPModel(nn.Module):
  def __init__ (self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu= nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [71]:
# create dataset
features = torch.rand(10,5)

#create model
model = MLPModel(features.shape[1])


# model.forward(features)
model(features)

tensor([[0.5902],
        [0.5975],
        [0.6043],
        [0.5924],
        [0.5987],
        [0.5947],
        [0.5881],
        [0.5957],
        [0.5957],
        [0.5991]], grad_fn=<SigmoidBackward0>)

In [72]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
MLPModel                                 [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [73]:
# sequential container

# create model with hidden network
class SeqModel(nn.Module):
  def __init__ (self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid())

  def forward(self, features):
    out = self.network(features)


    return out

In [74]:
# create dataset
features = torch.rand(10,5)

#create model
model = SeqModel(features.shape[1])

# model.forward(features)
model(features)

tensor([[0.4680],
        [0.4661],
        [0.4708],
        [0.5001],
        [0.5131],
        [0.4706],
        [0.4704],
        [0.4892],
        [0.4830],
        [0.4929]], grad_fn=<SigmoidBackward0>)

In [75]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [76]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [77]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace= True)
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [78]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [79]:
class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out


  def loss_function(self, y_pred , y):
      epsilon = 1e-7
      y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

      # Calculate loss
      loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1-y_pred)).mean()
      return loss



In [80]:
learning_rate = 0.1
epochs = 60

In [81]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.8197771310806274
Epoch: 2, Loss: 0.77751225233078
Epoch: 3, Loss: 0.7513142824172974
Epoch: 4, Loss: 0.7354360222816467
Epoch: 5, Loss: 0.7255520820617676
Epoch: 6, Loss: 0.7189599871635437
Epoch: 7, Loss: 0.714154839515686
Epoch: 8, Loss: 0.7103489637374878
Epoch: 9, Loss: 0.7071399688720703
Epoch: 10, Loss: 0.7043216228485107
Epoch: 11, Loss: 0.7017849683761597
Epoch: 12, Loss: 0.6994696259498596
Epoch: 13, Loss: 0.6973387598991394
Epoch: 14, Loss: 0.6953678727149963
Epoch: 15, Loss: 0.693539023399353
Epoch: 16, Loss: 0.6918381452560425
Epoch: 17, Loss: 0.6902531981468201
Epoch: 18, Loss: 0.6887742877006531
Epoch: 19, Loss: 0.6873922348022461
Epoch: 20, Loss: 0.6860992908477783
Epoch: 21, Loss: 0.6848882436752319
Epoch: 22, Loss: 0.6837528944015503
Epoch: 23, Loss: 0.6826871037483215
Epoch: 24, Loss: 0.6816859841346741
Epoch: 25, Loss: 0.6807447671890259
Epoch: 26, Loss: 0.679858922958374
Epoch: 27, Loss: 0.6790246963500977
Epoch: 28, Loss: 0.678238570690155
Epoch: 

# Built in  loss function

In [82]:
loss_function = nn.BCELoss()

In [83]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.624005913734436
Epoch: 2, Loss: 0.49617576599121094
Epoch: 3, Loss: 0.4230891168117523
Epoch: 4, Loss: 0.3751775324344635
Epoch: 5, Loss: 0.34085023403167725
Epoch: 6, Loss: 0.3147689998149872
Epoch: 7, Loss: 0.29411205649375916
Epoch: 8, Loss: 0.27723535895347595
Epoch: 9, Loss: 0.26311129331588745
Epoch: 10, Loss: 0.25106221437454224
Epoch: 11, Loss: 0.24062183499336243
Epoch: 12, Loss: 0.23145821690559387
Epoch: 13, Loss: 0.22332820296287537
Epoch: 14, Loss: 0.21604914963245392
Epoch: 15, Loss: 0.20948107540607452
Epoch: 16, Loss: 0.20351479947566986
Epoch: 17, Loss: 0.19806350767612457
Epoch: 18, Loss: 0.19305749237537384
Epoch: 19, Loss: 0.18843984603881836
Epoch: 20, Loss: 0.1841636449098587
Epoch: 21, Loss: 0.1801898032426834
Epoch: 22, Loss: 0.1764853298664093
Epoch: 23, Loss: 0.1730223447084427
Epoch: 24, Loss: 0.1697768270969391
Epoch: 25, Loss: 0.16672813892364502
Epoch: 26, Loss: 0.1638582944869995
Epoch: 27, Loss: 0.16115157306194305
Epoch: 28, Loss: 0.15

In [84]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5811018943786621


# built in optimizer

In [85]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

#define optimizer
optimizer = torch.optim.SGD(model.parameters(), learning_rate)
# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # zero gradients
  optimizer.zero_grad()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7062660455703735
Epoch: 2, Loss: 0.5339075922966003
Epoch: 3, Loss: 0.44322076439857483
Epoch: 4, Loss: 0.38762038946151733
Epoch: 5, Loss: 0.3494375944137573
Epoch: 6, Loss: 0.3212183117866516
Epoch: 7, Loss: 0.29928743839263916
Epoch: 8, Loss: 0.28161096572875977
Epoch: 9, Loss: 0.26696544885635376
Epoch: 10, Loss: 0.25456690788269043
Epoch: 11, Loss: 0.2438880354166031
Epoch: 12, Loss: 0.23455984890460968
Epoch: 13, Loss: 0.22631573677062988
Epoch: 14, Loss: 0.2189578264951706
Epoch: 15, Loss: 0.2123357355594635
Epoch: 16, Loss: 0.20633304119110107
Epoch: 17, Loss: 0.20085789263248444
Epoch: 18, Loss: 0.19583682715892792
Epoch: 19, Loss: 0.19121019542217255
Epoch: 20, Loss: 0.18692904710769653
Epoch: 21, Loss: 0.18295276165008545
Epoch: 22, Loss: 0.17924727499485016
Epoch: 23, Loss: 0.17578373849391937
Epoch: 24, Loss: 0.17253755033016205
Epoch: 25, Loss: 0.1694875806570053
Epoch: 26, Loss: 0.1666155308485031
Epoch: 27, Loss: 0.16390544176101685
Epoch: 28, Loss: 0.

In [86]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.573253333568573
