In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print("GPU available")
  print(torch.cuda.get_device_name(0))
else:
  print("GPU not available")

GPU available
Tesla T4


# Creating a tensor

In [ ]:
# using empty
torch.empty(2,3)

tensor([[-2.2044e-29,  4.4400e-41, -2.2044e-29],
        [ 4.4400e-41,  1.5077e-38,  0.0000e+00]])

In [ ]:
#chck type
a= torch.empty(2,2)
type(a)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.9048, 0.1430, 0.6097],
        [0.1118, 0.4046, 0.2039]])

In [ ]:
#seed
torch.rand(2,3)

tensor([[0.7263, 0.4655, 0.3644],
        [0.4763, 0.8215, 0.3045]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

# seed for reproducability

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#other ways
print("using arrange ->", torch.arange(0,10,2))

#using linspace
print ("using linspacce ->", torch.linspace(0,10,10))

#using eye
print("using eye ->", torch.eye(5))

#using full
print("using full -> ", torch.full((3,3),5))

using arrange -> tensor([0, 2, 4, 6, 8])
using linspacce -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor shape

In [ ]:
x =torch.tensor([[2,3,4],[5,6,7],[3,4,2],[3,4,5]])
print(x)

tensor([[2, 3, 4],
        [5, 6, 7],
        [3, 4, 2],
        [3, 4, 5]])


In [ ]:
x.shape

torch.Size([4, 3])

In [ ]:
torch.empty_like(x)

tensor([[3775254769757585408, 7307199746910528123, 8031081810286486131],
        [2459014175065138034, 7304682943622051171, 2318283022184637550],
        [6877682122580386594, 2322206441393452147, 7022349238375820336],
        [8872155185258193252, 8385529201757741858, 8104338990085533817]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [ ]:
# torch.rand_like(x) <-- this wont work because it generates using float

# Tensor datatype

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype =torch.float)

tensor([1., 2., 3.])

In [ ]:
#using to()
y =x.to(torch.float32)
y

tensor([[2., 3., 4.],
        [5., 6., 7.],
        [3., 4., 2.],
        [3., 4., 5.]])

In [ ]:
torch.rand_like(y)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770],
        [0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])

In [ ]:
torch.rand_like(x, dtype= torch.float32)

tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209],
        [0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])

# mathematical operations

# 1) Scalar

In [ ]:
x= torch.rand(3,3)
x

tensor([[0.3039, 0.6726, 0.5740],
        [0.9233, 0.9178, 0.7590],
        [0.7775, 0.6179, 0.3379]])

In [ ]:
#addition
x+2

tensor([[2.3039, 2.6726, 2.5740],
        [2.9233, 2.9178, 2.7590],
        [2.7775, 2.6179, 2.3379]])

In [ ]:
#subtraction
x-1

tensor([[-0.6961, -0.3274, -0.4260],
        [-0.0767, -0.0822, -0.2410],
        [-0.2225, -0.3821, -0.6621]])

In [ ]:
# mulltiplication
x*3

tensor([[0.9117, 2.0179, 1.7219],
        [2.7699, 2.7534, 2.2771],
        [2.3326, 1.8536, 1.0136]])

In [ ]:
# division
x/2

tensor([[0.1520, 0.3363, 0.2870],
        [0.4616, 0.4589, 0.3795],
        [0.3888, 0.3089, 0.1689]])

In [ ]:
# int divison
(x*100)//3

tensor([[10., 22., 19.],
        [30., 30., 25.],
        [25., 20., 11.]])

In [ ]:
#mod
((x*100)//3)%2

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [1., 0., 1.]])

In [ ]:
#power
x**2

tensor([[0.0924, 0.4524, 0.3294],
        [0.8525, 0.8424, 0.5761],
        [0.6045, 0.3818, 0.1142]])

# element wise opreation

In [ ]:
a= torch.rand(2,3)
b = torch.rand(2,3)

In [ ]:
print(a)
print(b)

tensor([[0.2170, 0.9454, 0.7116],
        [0.1157, 0.6574, 0.3451]])
tensor([[0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]])


In [ ]:
#add
a+b

tensor([[0.2624, 1.9251, 1.2663],
        [0.8025, 1.1494, 0.4199]])

In [ ]:
#sub
a-b

tensor([[ 0.1717, -0.0344,  0.1568],
        [-0.5710,  0.1653,  0.2704]])

In [ ]:
#multi
a*b

tensor([[0.0098, 0.9262, 0.3948],
        [0.0795, 0.3234, 0.0258]])

In [ ]:
#division
a/b

tensor([[4.7864, 0.9649, 1.2826],
        [0.1685, 1.3360, 4.6143]])

In [ ]:
c= torch.tensor([1,-2,-3])

In [ ]:
#abs
torch.abs(c)

tensor([1, 2, 3])

In [ ]:
#neg
torch.neg(c)

tensor([-1,  2,  3])

In [ ]:
#Floor
d= torch.tensor([1.32,3.4,5.6])
torch.floor(d)

tensor([1., 3., 5.])

In [ ]:
#round
torch.round(d)

tensor([1., 3., 6.])

In [ ]:
#ceil
torch.ceil(d)

tensor([2., 4., 6.])

In [ ]:
#clamp  clamping
torch.clamp(d,min=2, max=3)

tensor([2., 3., 3.])

# reduction operation


In [ ]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[6, 2, 9],
        [5, 0, 4]])

In [ ]:
#sum
torch.sum(e)

tensor(26)

In [ ]:
#sum along columns
torch.sum(e,dim=0)

tensor([11,  2, 13])

In [ ]:
#sum along rows
torch.sum(e,dim=1)

tensor([17,  9])

In [ ]:
#mean
f= torch.tensor([1,2,3,4,5,6], dtype=torch.float32)
print(f)
torch.mean(f)

tensor([1., 2., 3., 4., 5., 6.])


tensor(3.5000)

In [ ]:
# std
torch.std(f)

tensor(1.8708)

In [ ]:
#var
torch.var(f)

tensor(3.5000)

In [ ]:
# prod
torch.prod(f)

tensor(720.)

In [ ]:
# argmin
torch.argmin(f)

tensor(0)

In [ ]:
# argmax
torch.argmax(f)

tensor(5)

In [ ]:
torch.min(f)

tensor(1.)

In [ ]:
torch.max(f)

tensor(6.)